query CountInforReview($type: String!, $projectId: String!) {
    reviewsWithPagination(
      where: { galleries: { some: { contentType: { startsWith: $type } } }, projectId: { eq: $projectId } }
    ) {
      totalCount
    }
  }